# Tensors

In [67]:
import torch
import numpy as np

In [68]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [69]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [70]:
x_ones_float = torch.ones_like(x_data, dtype=torch.float)
print(x_ones_float)

x_ones_int = torch.ones_like(x_data, dtype=torch.int64)
print(x_ones_int)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1, 1],
        [1, 1]])


In [71]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.4821, 0.2303],
        [0.4497, 0.3410]])


In [72]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0578, 0.0446, 0.2656],
        [0.9443, 0.4473, 0.5205]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [73]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}\n")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu



In [74]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(f"Second last and last column:\n {tensor[:, -2:]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([0.7097, 0.6438, 0.1368, 0.2223])
First column: tensor([0.7097, 0.5368, 0.1720, 0.6970])
Last column: tensor([0.2223, 0.6522, 0.2337, 0.9525])
Second last and last column:
 tensor([[0.1368, 0.2223],
        [0.0640, 0.6522],
        [0.8648, 0.2337],
        [0.8646, 0.9525]])
tensor([[0.7097, 0.0000, 0.1368, 0.2223],
        [0.5368, 0.0000, 0.0640, 0.6522],
        [0.1720, 0.0000, 0.8648, 0.2337],
        [0.6970, 0.0000, 0.8646, 0.9525]])


In [75]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.7097, 0.0000, 0.1368, 0.2223, 0.7097, 0.0000, 0.1368, 0.2223, 0.7097,
         0.0000, 0.1368, 0.2223],
        [0.5368, 0.0000, 0.0640, 0.6522, 0.5368, 0.0000, 0.0640, 0.6522, 0.5368,
         0.0000, 0.0640, 0.6522],
        [0.1720, 0.0000, 0.8648, 0.2337, 0.1720, 0.0000, 0.8648, 0.2337, 0.1720,
         0.0000, 0.8648, 0.2337],
        [0.6970, 0.0000, 0.8646, 0.9525, 0.6970, 0.0000, 0.8646, 0.9525, 0.6970,
         0.0000, 0.8646, 0.9525]])


In [76]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will
# have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [77]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f'y1: {y1}')
print(f'y2: {y2}')
print(f'y3: {y3}')

y1: tensor([[0.5718, 0.5347, 0.2923, 0.8246],
        [0.5347, 0.7176, 0.3001, 1.0506],
        [0.2923, 0.3001, 0.8321, 1.0902],
        [0.8246, 1.0506, 1.0902, 2.1405]])
y2: tensor([[0.5718, 0.5347, 0.2923, 0.8246],
        [0.5347, 0.7176, 0.3001, 1.0506],
        [0.2923, 0.3001, 0.8321, 1.0902],
        [0.8246, 1.0506, 1.0902, 2.1405]])
y3: tensor([[0.5718, 0.5347, 0.2923, 0.8246],
        [0.5347, 0.7176, 0.3001, 1.0506],
        [0.2923, 0.3001, 0.8321, 1.0902],
        [0.8246, 1.0506, 1.0902, 2.1405]])


In [78]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [79]:
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f'z1: {z1}')
print(f'z2: {z2}')
print(f'z3: {z3}')

z1: tensor([[0.5036, 0.0000, 0.0187, 0.0494],
        [0.2881, 0.0000, 0.0041, 0.4254],
        [0.0296, 0.0000, 0.7479, 0.0546],
        [0.4858, 0.0000, 0.7475, 0.9072]])
z2: tensor([[0.5036, 0.0000, 0.0187, 0.0494],
        [0.2881, 0.0000, 0.0041, 0.4254],
        [0.0296, 0.0000, 0.7479, 0.0546],
        [0.4858, 0.0000, 0.7475, 0.9072]])
z3: tensor([[0.5036, 0.0000, 0.0187, 0.0494],
        [0.2881, 0.0000, 0.0041, 0.4254],
        [0.0296, 0.0000, 0.7479, 0.0546],
        [0.4858, 0.0000, 0.7475, 0.9072]])


In [80]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

6.106230735778809 <class 'float'>


In [81]:
print(f"tensor (before): \n{tensor} \n")
tensor.add_(5)
print(f"tensor (after): \n{tensor} \n")

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

tensor (before): 
tensor([[0.7097, 0.0000, 0.1368, 0.2223],
        [0.5368, 0.0000, 0.0640, 0.6522],
        [0.1720, 0.0000, 0.8648, 0.2337],
        [0.6970, 0.0000, 0.8646, 0.9525]]) 

tensor (after): 
tensor([[5.7097, 5.0000, 5.1368, 5.2223],
        [5.5368, 5.0000, 5.0640, 5.6522],
        [5.1720, 5.0000, 5.8648, 5.2337],
        [5.6970, 5.0000, 5.8646, 5.9525]]) 

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
